SHOP-319 joy_session_id cookie secure = true
joylifeinc/server-core pull request #145
Opened 2022-06-23 11:41 UTC by lmaranhao

2022-06-24 02:36 UTC, cantremember requested changes
## i overlooked something important

please see the updated JIRA description and it's need for `deriveRuntimeEnvironment`

2022-06-30 19:36 UTC, cantremember approved these changes
## minor changes

once

- those revs are made
- the CircleCI build passes
- and you determine that it works as intended when integrated

then this is ✅ and can be merged.  i would consider this to be a MINOR rev -- please publish a new version accordingly per the README file instructions

2022-06-30 19:36 UTC, cantremember commented on src/middleware/session.ts
> +    secure: deriveRuntimeEnvironment().isProduction,
```
// enforce TLS in Production mode only, to avoid constraining Development to 'https://'
```

2022-06-30 19:36 UTC, cantremember commented on src/utils/dotenv.ts
> +export interface RuntimeEnvironment {
`LoadDotEnvResult` should extend this as well

2022-06-30 19:36 UTC, cantremember commented on src/middleware/session.ts
> +import { deriveRuntimeEnvironment } from '../index';
the Node 6 build step in CircleCI is failing.  i think it's because of this line

going with `from '../utils/dotenv'` should fix the issue -- i tried it out here successfully https://app.circleci.com/pipelines/github/joylifeinc/server-core/494/workflows/74a45101-b89f-43a7-a38b-585d6e9e4bea/jobs/1064

2022-06-30 21:46 UTC, lmaranhao commented on src/utils/dotenv.ts
> +export interface RuntimeEnvironment {
true

2022-06-30 21:48 UTC, lmaranhao commented on src/middleware/session.ts
> +    secure: deriveRuntimeEnvironment().isProduction,
done

2022-06-30 21:49 UTC, lmaranhao commented on src/middleware/session.ts
> +import { deriveRuntimeEnvironment } from '../index';
done

2022-06-30 22:04 UTC, lmaranhao commented
I was able to test this starting stich_service `NODE_ENV=production` and mitmdump in my local (notice the `Secure;` below)
```
curl -i --insecure https://local.withjoy.com:8443/healyHTTP/2 200 
x-powered-by: Express
access-control-allow-origin: *
access-control-allow-credentials: true
set-cookie: joy_session_id=2ff98b54f849f24c9f3f91f3126a98951ba8fccb4d6831cf; Max-Age=157680000; Domain=.withjoy.com; Path=/; Expires=Sun, 03 Jan 2038 00:00:00 GMT; HttpOnly; Secure; SameSite=Lax
content-type: text/plain; charset=utf-8
content-length: 2
etag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
date: Thu, 30 Jun 2022 21:58:15 GMT 
```

if I start it with `NODE_ENV=development`  I would get the response below  (notice the missing `Secure;` below)
```
curl -i --insecure https://local.withjoy.com:8443/healthy
HTTP/2 200 
x-powered-by: Express
access-control-allow-origin: *
access-control-allow-credentials: true
set-cookie: joy_session_id=4532da9ddf590a62ec0a6cdb92e7bcf171e8b8668a5e9d33; Max-Age=157680000; Domain=.withjoy.com; Path=/; Expires=Sun, 03 Jan 2038 00:00:00 GMT; HttpOnly; SameSite=Lax
content-type: text/plain; charset=utf-8
content-length: 2
etag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
date: Thu, 30 Jun 2022 21:57:46 GMT
```

2022-07-01 16:57 UTC, merged