SHOP-516: HeathCheckState Util Upgrade
joylifeinc/server-core pull request #148
Opened 2022-08-02 21:08 UTC by kaiyuewang1998

This PR is in conjunction with a PR in product_service to apply the `HealthCheckState` upgrade during Catalog Sync.

2022-08-04 02:15 UTC, cantremember requested changes
## reviewed

two stylistic changes -- thank you for being patient with how i dole those out

the behavior i ask about isn't quite what we want.  there's another way

run this by me once more and i'll get it ✅ed

2022-08-04 02:15 UTC, cantremember commented on src/utils/healthCheck/utils.ts
> +export interface HealthCheckStatePayload {
i would say that it's more of an `Options`

2022-08-04 02:15 UTC, cantremember commented on src/utils/healthCheck/utils.ts
> +  constructor(payload: HealthCheckStatePayload) {
for backwards compatability, please make it `options?` optional

2022-08-04 02:15 UTC, cantremember commented on src/utils/healthCheck/utils.ts
> +    this._prevState = this._value;
i see what you did there.  what is the behavior if

- the `state: HealthCheckState` was false
- the State logs
- state.set(false)
- and then its healthChecker gets called

2022-08-04 02:15 UTC, cantremember commented on src/utils/healthCheck/utils.ts
> +          action: 'healthCheckStateUnhealthy',
`action` is best when it's short, and it always gets queried along with `source`.  if we keep thinking of our log patterns that way, a shorter 'unhealthy' is enough

2022-08-04 18:52 UTC, cantremember commented on src/utils/healthCheck/utils.ts
> +export interface HealthCheckStatePayload {
thanks, @kaiyuewang1998 .  i like the way it reads now

2022-08-04 19:15 UTC, cantremember approved these changes
## final pass

please address my feedback, then ✅

2022-08-04 19:15 UTC, cantremember commented on src/utils/healthCheck/utils.spec.ts
> +        // it (should never report to telemetry no matter how many times called)
💯

2022-08-04 19:15 UTC, cantremember commented on src/utils/healthCheck/utils.spec.ts
> +        await state.healthChecker(CONTEXT);
continuing with your line of thought here,

```suggestion
        await state.healthChecker(CONTEXT);

        //it (should not log another telmetry info)
        await state.healthChecker(CONTEXT);
```

2022-08-04 19:15 UTC, cantremember commented on src/utils/healthCheck/utils.ts
> +  tag?: string,
are you sure it should be optional?  `loggingStrategy` with no `tag` is probably a bad idea

2022-08-04 19:38 UTC, kaiyuewang1998 commented on src/utils/healthCheck/utils.ts
> +  tag?: string,
Okay cool, I was wondering about that. So then should I also have a default tag if there are no options passed in.
Since the default loggingStrategy is `onChange`, should there be a default tag associated with that?

2022-08-05 02:29 UTC, cantremember commented on src/utils/healthCheck/utils.ts
> +  tag?: string,
damn.  good point

i like the choice of default behavior.  so we have to make up a tag.  'healthCheckState'?

2022-08-05 02:30 UTC, cantremember reviewed
## oooh, nice catch

yeah.  we need a default tag

2022-08-15 20:35 UTC, merged