SHOP-746 add deployed informational route
joylifeinc/server-core pull request #171
Opened 2022-12-22 12:05 UTC by vikas-mindpath

2022-12-22 12:35 UTC, tomnocon commented on src/ops/deployed.router.ts
> +  constructor(readonly deployedJson: any, readonly app: string) {
I think, it would be better to provide an interface here in constructor instead of using any types. Example:
```typescript
interface DeployedInfo {
  serviceName: string;
  deployedSHA: string;
  deployedTag: string;
  launchedAt: Date;
}
```
I only have uncertainty about the `launchedAt` property, whether it should be computed by service or by server core. I'm leaving this decision to you.

2022-12-22 12:38 UTC, tomnocon requested changes
Looks good except using `any` type in constructor. I think it would be better to have strong typing there.

2022-12-22 14:50 UTC, vikas-mindpath commented on src/ops/deployed.router.ts
> +  constructor(readonly deployedJson: any, readonly app: string) {
Yes I was working on that part but looks like you have reviewed it before but Thanks I will use your naming convention. 

RE: **launchedAt** I would like to keep this in server-core, caller service need not worry about this property.

2022-12-22 14:55 UTC, tomnocon commented on src/ops/deployed.router.ts
> +  constructor(readonly deployedJson: any, readonly app: string) {
Okey, thank you for addressing my feedback 🙏

2022-12-22 14:56 UTC, tomnocon approved these changes
Now it looks good to me. Thank you 👍

2022-12-23 07:07 UTC, cantremember approved these changes
lgtm ✅

2022-12-23 07:38 UTC, merged