SHOP-1174 amend upsert helper to omit overwrite on key
joylifeinc/server-core pull request #173
Opened 2022-12-26 08:26 UTC by ehimah

This PR amends the `upsertForInsertQueryBuilder` function by introducing aN `omitKeyFromOverwrite` option.

This new query builder helps to exclude the primary `key` column from being overwritten on `CONFLICT UPDATE`

2022-12-28 07:13 UTC, vikas-mindpath requested changes
I have one suggestion otherwise looks good to me.

2022-12-28 07:13 UTC, vikas-mindpath commented on src/utils/typeorm/inserts.ts
> +    omitProperties.push('key');
Shouldn't we always omit key on update ? I don't see any reason to update the key.

2022-12-28 11:42 UTC, ehimah commented on src/utils/typeorm/inserts.ts
> +    omitProperties.push('key');
I really thought about this point, even though it makes sense from what we want to achieve in this [ticket](https://withjoy.atlassian.net/browse/SHOP-1174), 

However I kept this way because setting the `omitKeyFromOverwrite` to default `true` becomes a breaking change from an API design PoV. 

@cantremember what do you think?

2022-12-28 23:33 UTC, ehimah commented on src/utils/typeorm/inserts.ts
> +    omitProperties.push('key');
actually on a second thought, I think it's smart to keep this default true. I'll update it

2022-12-29 14:43 UTC, vikas-mindpath approved these changes
I have added one suggestion with that it's **lgtm**

2022-12-29 14:43 UTC, vikas-mindpath commented on src/utils/typeorm/inserts.ts
> +  const omitProperties = options?.omitProperties || ['key'];
```suggestion
  const omitProperties = options?.omitProperties || [];
  // key will be omitted by default
  omitProperties.push('key');
```

2022-12-29 14:45 UTC, vikas-mindpath commented on src/utils/typeorm/inserts.ts
> +  const omitProperties = options?.omitProperties || ['key'];
I also think we should write test case for this.

2022-12-29 14:47 UTC, vikas-mindpath approved these changes

2022-12-30 14:31 UTC, merged

2023-01-05 03:12 UTC, cantremember reviewed
## reasonable

...

2023-01-05 03:12 UTC, cantremember commented on src/utils/typeorm/inserts.ts
> +  omitProperties.push('key');
as long as we always have a `key` in every Table, we're good