Feature shop 1124 refactor context for authenticated user
joylifeinc/server-core pull request #175
Opened 2023-02-14 13:06 UTC by vikas-mindpath

2023-02-16 23:27 UTC, cantremember requested changes
## a small change in strategy

as noted below.  assuming you think it's a viable strategy

2023-02-16 23:27 UTC, cantremember commented on src/server/apollo.context.ts
> +      const decodedAuthorization = verifyAll(this.tokenConfig, this.token);
🤦 i see why you're doing this.  and it means that *every* Service must provide *all* of.   the Auth0 token signing configs.  we want to avoid that

how does this sound as an alternate approach?
- extend `IdentityUserJWTPayload` with `{ auth0Id: string }`
- update `identity_service` to provide that in its signed JWT
- compare the auth0Id received in the verified Identity User JWT against the un-verified decoded `sub` of the Context's token - if they match, you can trust them both

yes, it does touch upon a few parts of the effort that are "done", but the need didn't reveal itself until now

(this technique would not help us in `stitch_service`)

2023-02-16 23:27 UTC, cantremember commented on src/server/apollo.context.ts
> +  public me = (overrides?: IServiceCallerOverrides): void => {
i think `overrides` goes away -- we never make a ServiceCall

just use the headers in the `req`

2023-02-16 23:27 UTC, cantremember commented on src/server/apollo.context.spec.ts
> +            source: 'context#me',
you can see pattern this in the rest of the file

```suggestion
            source: 'apollo',
```

2023-02-22 14:38 UTC, cantremember commented on src/authentication/verify.token.ts
> +  secret: {
unify type with JWTSigningConfig

2023-02-22 14:38 UTC, cantremember commented on src/authentication/verify.token.ts
> +export interface JwtSigningValues {
please use either "Jwt" or "JWT" consistently in camel-case consts

2023-02-22 14:38 UTC, cantremember commented on src/server/apollo.context.spec.ts
> +const USER_DATA = {
```suggestion
const USER_DATA: ContextUserFragment = {
```

that's the shape it should have, right?

2023-02-22 14:38 UTC, cantremember commented on src/server/apollo.context.spec.ts
> +      secret: {
indentation cleanup, please

2023-02-22 14:38 UTC, cantremember commented on src/server/apollo.context.spec.ts
> +      //No Params
duplicate ❌

2023-02-22 14:38 UTC, cantremember commented on src/server/apollo.context.spec.ts
> +      //No Params
duplicate ❌

2023-02-22 14:38 UTC, cantremember commented on src/server/apollo.context.ts
> +        throw new Error('userjwt is missing');
i stared at this for a while.  i don't think `Context.me` should throw as many Errors as the new code does.  i think these are simply NO_USER conditions -- just halt processing

what do you think about a `telemetry.warn` here?  if this scenario happens, i don't want it to fail the whole request, but i also don't want it to get overlooked -- and when debugging request processing, it'd be important to know that we didn't get a JWT.  with `{ action: 'me' }` please

2023-02-22 14:38 UTC, cantremember commented on src/server/apollo.context.ts
> +        throw new Error('Auth token and user jwt mismatch');
i think this is a genuine Error 👍  -- it should never happen, and if it does, it's almost certainly a hack

2023-02-22 14:41 UTC, cantremember requested changes
## still need a bit of work

but we are in the final stages of this

2023-02-22 15:25 UTC, cantremember requested changes

2023-02-22 15:25 UTC, cantremember commented on src/index.ts
> +  JWTSigningConfig
please expose `ContextUserFragment` as well.  and correct the 'dist/' imports for it in Stitch + Identity

and please move these up towards where the other related exports live in this big file listing 🙏

2023-02-23 14:07 UTC, vikas-mindpath commented on src/server/apollo.context.ts
> +        throw new Error('userjwt is missing');
Agreed 💯

2023-02-24 04:30 UTC, cantremember approved these changes
## yep

thank you for the iterations on this.  it's looking good ✅

2023-02-24 12:02 UTC, merged