Feat shop 1561 reset apollo package baseline to federation
joylifeinc/server-core pull request #183
Opened 2023-03-23 11:43 UTC by vikas-mindpath

2023-03-23 11:54 UTC, vikas-mindpath commented on src/server/apollo.server.ts
> -    context: (ctx: any) => {
Context will be added on apollo **expressMiddleware**

2023-03-24 04:57 UTC, cantremember requested changes
## that's a lot of stuff

this could not have been easy.  it seems solid 👍 

yet there are a number of places that i feel need an adjust.

2023-03-24 04:57 UTC, cantremember commented on test/apollo/core.types.date.ts
> +  });
not needed if there's a `client` implementation

2023-03-24 04:57 UTC, cantremember commented on test/apollo/core.types.date.ts
> +        mocks: {
ah -- i needed to see it in action.

i recommend that you name this property `typeMocks`, even if Apollo calls it `mocks` -- because "mocks" could mean just about anything to someone not familiar with what they mean

2023-03-24 04:57 UTC, cantremember commented on test/apollo/core.types.date.ts
> +        mocks: {
## wait ...

what happens if you *don't* mock Timestamp.  we didn't have to mock it before

2023-03-24 04:57 UTC, cantremember commented on test/apollo/core.types.date.ts
> +        contextValue: new Context()
you didn't have to do this in 'test/apollo/core.types.color.ts' ... why here?

2023-03-24 04:57 UTC, cantremember commented on test/apollo/core.types.date.ts
> +        })
taking this code back to the way it was before your revs ... the `context` instance being 'setup' is being injected with that locale

is there an reason that your `client` methods shouldn't do `{ contextValue: context, ... }` and just pass through the `setup.context` instance that way?

2023-03-24 04:57 UTC, cantremember commented on test/apollo/errorPipeline.ts
> +        } as unknown as Request
the `Reflect.set(...)` technique could be used here on `setup.context` just like it was for LOCALE_QUEBECOIS

just reading up to this point, i believe the amount of code changes in this PR would drop by more than half, maybe even 300%, if you were to implement a `client` with query + mutate

2023-03-24 04:57 UTC, cantremember commented on test/apollo/virtualEvent.ts
> +          urlLinkText: '', //default mock value for string in empty string
... but only because of your choices in implementing `defaultMocks`.  it could just as easily resolve null

2023-03-24 04:57 UTC, cantremember commented on test/integration/server.ts
> +      .expect(418, `I'm a Teapot`);
wow 😮 that changed

2023-03-24 14:59 UTC, vikas-mindpath commented on src/server/apollo.server.ts
> -    context: (ctx: any) => {
in apollo server we don't have context key so **contextFunc** is use less here we can remove it. WE can add contextFunc inside [Server](https://github.com/joylifeinc/server-core/blob/feat_SHOP-1561_reset_apollo_package_baseline_to_federation/src/server/server.ts#:~:text=interface-,ServerConstructor,-%3CServerContext%20extends) argument and can use inside [expressMiddleware](https://github.com/joylifeinc/server-core/blob/feat_SHOP-1561_reset_apollo_package_baseline_to_federation/src/server/server.ts#:~:text=.use(-,expressMiddleware,-(apollo%2C)/

2023-03-24 15:15 UTC, vikas-mindpath commented on src/server/server.ts
> -      cors: false,
IN previous version if cors is false we are not adding cors inside middleware and not also we are not adding cors in middleware so I think both are same.

Let's discuss this.

2023-03-24 15:16 UTC, vikas-mindpath commented on src/server/server.ts
> +          return req.context;
Yes we are able to get context in event and photo.

2023-03-24 15:18 UTC, vikas-mindpath commented on test/apollo/core.types.color.ts
> +    await setup.apollo.stop();
Yeah that would be good approach 💯

2023-03-24 15:19 UTC, vikas-mindpath commented on test/apollo/core.types.date.ts
> +        mocks: {
It will throw error timestamp not mocked.

2023-03-24 15:28 UTC, vikas-mindpath commented on test/apollo/core.types.date.ts
> +        contextValue: new Context()
Because context is used here to fetch locale value but when we run 'test/apollo/core.types.color.ts'  context never used so its not throwing erorr.

2023-03-24 15:38 UTC, vikas-mindpath commented on test/apollo/core.types.date.ts
> +        })
Yes that can reverted with client implementation.

2023-03-24 15:45 UTC, vikas-mindpath commented on test/apollo/virtualEvent.ts
> +          urlLinkText: '', //default mock value for string in empty string
I have override because defaultMocks value of string in mock library is "Hello World" 

![image](https://user-images.githubusercontent.com/74169343/227573803-461830e7-0b9c-42e4-aafc-acede66233b4.png)

2023-03-24 15:47 UTC, vikas-mindpath commented on src/server/server.ts
> -      cors: false,
IN previous version if cors is false we are not adding cors inside middleware and not also we are not adding cors in middleware so I think both are same.

Let's discuss this.

2023-04-03 05:59 UTC, cantremember requested changes
## some minor feedback

this should be the end of it.  plesae make your revisions & let me know when it's ready for a final 👀 

what were you planning on calling the package version?  if i'm 👍 wih your work, i can merge & build & push the new code during your overnight

2023-04-03 05:59 UTC, cantremember commented on src/server/apollo.errorPipeline.ts
> +        const context = requestContext.contextValue;
i'm a bit confused -- i don't see the property on the Request being named 'contextValue' anywhere else than this line, including in `deriveContextFromRequest` (which i think should be used here)

2023-04-03 05:59 UTC, cantremember commented on src/server/apollo.errorPipeline.ts
> +        const context = requestContext.contextValue;
## in fact,

with regards to `deriveContextFromRequest`.  can this

```
  const context = (<any>req).context;
  return (context ? (context as T) : undefined);
```

be made any cleaner by use of `RequestWithContext<T>`?

2023-04-03 05:59 UTC, cantremember commented on src/server/apollo.server.ts
> +    logger: telemetry,
just a clarifying comment i'd like to see added:

```suggestion
    logger: telemetry,  // the global singleton
```

and `T`is probably best renamed `ServerContext` as i see you've been doing elsewhere

2023-04-03 05:59 UTC, cantremember commented on src/server/server.ts
> +          return req.context;
excellent 👍 does `deriveContextFromRequest` work if used in line 163?

2023-04-03 09:12 UTC, vikas-mindpath commented on src/server/apollo.errorPipeline.ts
> +        const context = requestContext.contextValue;
Here contextValue is coming from **GraphQLRequestContext** it is type coming from apollo.

Context which we are passing from middleware can be retrived from contextValue.

2023-04-04 13:41 UTC, cantremember commented on src/server/server.ts
> -      cors: false,
i agree

2023-04-04 15:10 UTC, cantremember commented on src/server/apollo.server.ts
> -    context: (ctx: any) => {
this has been addressed with a clean pattern 👍

2023-04-04 15:11 UTC, cantremember commented on src/server/server.ts
> +          return req.context;
this is all working & implemented as expected 👍

2023-04-11 19:36 UTC, merged